### ISSUE TITLE
Dome of Heaven Calendar won't load

### ISSUE THREAD

**Issue by ichabod801** [ichabod801/dm#26]
Trying to load the Dome of Heaven Calendar gives this error:

```python
Traceback (most recent call last):
  File "C:\Users\spam\Documents\Roleplaying\dm\egor.py", line 1716, in onecmd
    return super().onecmd(line)
  File "C:\Users\spam\anaconda3\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "C:\Users\spam\Documents\Roleplaying\dm\egor.py", line 998, in do_set
    self.load_campaign()
  File "C:\Users\spam\Documents\Roleplaying\dm\egor.py", line 1564, in load_campaign
    self.campaign.calendar.set_year(self.time.year)
  File "C:\Users\spam\Documents\Roleplaying\dm\gtime.py", line 248, in set_year
    self.current_year = self.year_table(year)
  File "C:\Users\spam\Documents\Roleplaying\dm\gtime.py", line 385, in year_table
    cycle.expand_table(table, self)
  File "C:\Users\spam\Documents\Roleplaying\dm\gtime.py", line 602, in expand_table
    overage_period = self.periods[last_year_periods - 1]
IndexError: list index out of range
```

**Comment by ichabod801** [comment]
This could be a problem with the calendar definition. But I can't track that down with the code as it is, so I'm going to add more reprs and track down the problem.

**Comment by ichabod801** [comment]
It was two problems. First, I was calculating the ceiling manually and incorrectly, causing problems with even numbered fractional cycles. Second, the calendar definition was off for Obus.
